import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import process from "node:process";
import { configuredAgentProviders, normalizeAgentProvider, zcodeAccountProviderConfig, zcodeLaunchConfig } from "../apps/bridge/agentProviders.js";
import { ZcodeAgentClient } from "../apps/bridge/zcodeAgent.js";

assert.equal(normalizeAgentProvider("zcode"), "zcode");
assert.equal(normalizeAgentProvider("unknown"), "codex");
const credentialsPath = join(tmpdir(), `wps-connector-zcode-credentials-${process.pid}-${randomUUID()}.json`);
const builtinConfigPath = join(tmpdir(), `wps-connector-zcode-builtin-${process.pid}-${randomUUID()}.json`);
writeFileSync(credentialsPath, JSON.stringify({ "account-provider:coding-plan:account:bigmodel-individual-coding-plan:account:test:api-key": "enc:v1:encrypted-test-value" }));
writeFileSync(builtinConfigPath, JSON.stringify({ revision: 28, config: { providerConfigRules: { templateRules: [{ templateId: "bigmodel-api", config: { api: { type: "anthropic-messages", baseUrl: "https://example.invalid" }, builtinModelIds: ["GLM-5.3", "GLM-5.3-Flash"] } }] } } }));
const testEnv = { WPS_CONNECTOR_ZCODE_COMMAND: process.execPath, WPS_CONNECTOR_ZCODE_SCRIPT: process.execPath, WPS_CONNECTOR_ZCODE_CREDENTIALS: credentialsPath, WPS_CONNECTOR_ZCODE_BUILTIN_CONFIG: builtinConfigPath, WPS_CONNECTOR_ZCODE_API_KEY: "test-key" };
const launch = zcodeLaunchConfig(testEnv);
assert.equal(launch.available, true);
assert.equal(launch.configured, true);
assert.equal(launch.standaloneReady, true);
assert.deepEqual(launch.model, { providerId: "account:bigmodel-individual-coding-plan", modelId: "GLM-5.3" });
assert.equal(zcodeAccountProviderConfig(testEnv, launch).basedOnZCodeBuiltinRevision, "28");
const encryptedOnly = zcodeLaunchConfig({ ...testEnv, WPS_CONNECTOR_ZCODE_API_KEY: "" });
assert.equal(encryptedOnly.credentialMode, "encrypted-gui-store");
assert.equal(encryptedOnly.standaloneReady, false);
const providers = configuredAgentProviders(testEnv);
assert.deepEqual(providers.map((item) => item.id), ["codex", "zcode"]);
assert.equal(providers.find((item) => item.id === "zcode")?.available, true);
const client = new ZcodeAgentClient({ command: process.execPath, args: [join(process.cwd(), "tests/fixtures/fake-zcode-app-server.js")], model: { providerId: "fake", modelId: "test-model", options: { reasoningLevel: "low" } }, providerAccountConfig: { revision: "test-revision", basedOnZCodeBuiltinRevision: "28", providers: { fake: {} }, states: { fake: { availability: "available", entitled: true, current: true } } } });
const runtimeHeaderWrites = [];
client.child = { stdin: { writable: true, write: (line) => runtimeHeaderWrites.push(JSON.parse(line)) } };
await client.handleServerRequest({ id: "runtime-header-test", method: "interaction/requestProviderRuntimeHeaders", params: { providerId: "fake", modelSelection: { providerId: "fake", modelId: "test-model" } } });
assert.equal(runtimeHeaderWrites.at(-1)?.result?.headersApplied, false);
client.child = null;
const created = await client.startThread({ cwd: process.cwd() });
assert.equal(created.threadId, "zcode-test-session");
const history = await client.readThread(created.threadId);
assert.equal(history.messages[0]?.text, "历史回复");
await client.startTurn(created.threadId, "测试");
await new Promise((resolve) => setTimeout(resolve, 30));
assert.equal(client.getRun(created.threadId)?.status, "completed");
client.child?.kill();
rmSync(credentialsPath, { force: true });
rmSync(builtinConfigPath, { force: true });
console.log("agent provider tests passed");
